"""refactory email_inform_record table...

Revision ID: 40f8cc9bdfd8
Revises: 4f778c016017
Create Date: 2017-12-21 14:44:51.176999

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '40f8cc9bdfd8'
down_revision = '4f778c016017'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_inform_record', sa.Column('email_name', sa.String(length=32), nullable=True))
    op.add_column('email_inform_record', sa.Column('order_id', sa.Integer(), nullable=True))
    op.drop_column('email_inform_record', 'record')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_inform_record', sa.Column('record', mysql.TEXT(), nullable=True))
    op.drop_column('email_inform_record', 'order_id')
    op.drop_column('email_inform_record', 'email_name')
    # ### end Alembic commands ###
