"""table 'order' add column 'order_no', 'tracking_no'

Revision ID: 641fec98e54e
Revises: 3dc586d55ca1
Create Date: 2017-12-22 14:19:17.615008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '641fec98e54e'
down_revision = '3dc586d55ca1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('order_no', sa.String(length=64), nullable=True))
    op.add_column('order', sa.Column('tracking_no', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'tracking_no')
    op.drop_column('order', 'order_no')
    # ### end Alembic commands ###
