"""table'login_email' add column 'retry'

Revision ID: 8f6790743d91
Revises: 641fec98e54e
Create Date: 2017-12-22 20:53:47.071820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f6790743d91'
down_revision = '641fec98e54e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login_email', sa.Column('retry', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('login_email', 'retry')
    # ### end Alembic commands ###
